"""Central registry for machine-readable API error codes."""

COMMON_VALIDATION_INVALID_REQUEST = "common.validation.invalid_request"
COMMON_INTERNAL_UNEXPECTED_ERROR = "common.internal.unexpected_error"
COMMON_RATE_LIMIT_EXCEEDED = "common.rate_limit.exceeded"

PIPELINE_TASK_NOT_FOUND = "pipeline.task.not_found"
PIPELINE_TASK_INVALID_ID = "pipeline.task.invalid_id"
PIPELINE_STATUS_LOOKUP_FAILED = "pipeline.status.lookup_failed"
PIPELINE_MATCH_ALREADY_RUNNING = "pipeline.match.already_running"
PIPELINE_MATCH_START_FAILED = "pipeline.match.start_failed"
PIPELINE_MATCH_STOP_NOT_FOUND = "pipeline.match.stop_not_found"
PIPELINE_MATCH_STOP_FAILED = "pipeline.match.stop_failed"

PIPELINE_RESUME_UPLOAD_IN_PROGRESS = "pipeline.resume.upload_in_progress"
PIPELINE_RESUME_NOT_READY = "pipeline.resume.not_ready"
PIPELINE_RESUME_UPLOAD_NOT_FOUND = "pipeline.resume.upload_not_found"
PIPELINE_RESUME_UPLOAD_NOT_RETRYABLE = "pipeline.resume.upload_not_retryable"
PIPELINE_RESUME_REUPLOAD_REQUIRED = "pipeline.resume.reupload_required"
PIPELINE_RESUME_FILE_REQUIRED = "pipeline.resume.file_required"
PIPELINE_RESUME_FILE_EMPTY = "pipeline.resume.file_empty"
PIPELINE_RESUME_FILE_UNSUPPORTED = "pipeline.resume.file_unsupported"
PIPELINE_RESUME_FILE_TOO_LARGE = "pipeline.resume.file_too_large"
PIPELINE_RESUME_HASH_MISMATCH = "pipeline.resume.hash_mismatch"
