#!/usr/bin/env python3
"""Test RequirementMatcher."""
import pytest
from unittest.mock import Mock

from core.matcher.requirement_matcher import RequirementMatcher
from core.matcher.models import ResumeEvidenceUnit
from core.matcher.similarity import SimilarityCalculator
from core.config_loader import MatcherConfig


@pytest.fixture
def mock_ai_service():
    mock = Mock()
    mock.generate_embedding.return_value = [0.1] * 1024
    return mock


@pytest.fixture
def mock_ai_service_with_multiple_returns():
    mock = Mock()
    
    def side_effect(text):
        if "Python" in text:
            return [0.8, 0.2, 0.1] * 1024
        elif "Other" in text:
            return [0.8, 0.2, 0.1] * 1024
        else:
            return [0.1, 0.2, 0.3] * 1024
    
    mock.generate_embedding.side_effect = side_effect
    return mock


@pytest.fixture
def sample_evidence_units():
    return [
        ResumeEvidenceUnit(
            id="reu_001",
            text="Python development",
            source_section="skills",
            tags={"type": "skill"},
            embedding=[0.8, 0.2, 0.1] * 1024
        ),
        ResumeEvidenceUnit(
            id="reu_002",
            text="Other skill",
            source_section="skills",
            tags={"type": "skill"},
            embedding=[0.9, 0.8, 0.7] * 1024
        ),
        ResumeEvidenceUnit(
            id="reu_003",
            text="AWS cloud",
            source_section="experience",
            tags={"company": "TechCorp", "type": "description"},
            embedding=[0.5, 0.3, 0.2] * 1024
        )
    ]


@pytest.fixture
def mock_requirement():
    from database.models import JobRequirementUnit
    req = Mock(spec=JobRequirementUnit)
    req.id = "req-001"
    req.text = "Python expertise"
    req.req_type = "required"
    req.embedding_row = Mock()
    req.embedding_row.embedding = [0.85, 0.15, 0.25] * 341
    req.min_years = None
    return req


@pytest.fixture
def mock_requirement_no_embedding():
    from database.models import JobRequirementUnit
    req = Mock(spec=JobRequirementUnit)
    req.id = "req-002"
    req.text = "Python expertise"
    req.req_type = "required"
    req.embedding_row = None
    req.min_years = None
    return req


@pytest.fixture
def matcher_config():
    return MatcherConfig(
        similarity_threshold=0.5,
        embedding_dimensions=1024
    )


def test_requirement_matcher_covered(sample_evidence_units, mock_requirement, matcher_config, mock_ai_service_with_multiple_returns):
    """Test RequirementMatcher matches evidence to requirements."""
    config = MatcherConfig(similarity_threshold=0.5)
    matcher = RequirementMatcher(
        ai_service=mock_ai_service_with_multiple_returns,
        similarity_calc=SimilarityCalculator(),
        similarity_threshold=config.similarity_threshold
    )
    
    matched, missing = matcher.match_requirements(sample_evidence_units, [mock_requirement])
    
    assert len(matched) == 1
    assert len(missing) == 0
    assert matched[0].is_covered == True
    assert matched[0].similarity >= 0.5


def test_requirement_matcher_not_covered(mock_requirement_no_embedding, mock_ai_service):
    """Test RequirementMatcher when requirement is not covered.
    
    Uses evidence with embeddings that are very dissimilar to requirement.
    """
    # Create evidence units with embeddings very dissimilar to requirement
    # The requirement embedding will be generated by the AI service
    # Use orthogonal vectors which give normalized similarity of 0.5
    mock_ai_service.generate_embedding.return_value = [1.0, 0.0, 0.0] * 1024
    
    dissimilar_evidence = [
        ResumeEvidenceUnit(
            id="reu_dissimilar",
            text="Completely unrelated skill",
            source_section="skills",
            tags={"type": "skill"},
            embedding=[0.0, 1.0, 0.0] * 1024
        )
    ]
    
    matcher = RequirementMatcher(
        ai_service=mock_ai_service,
        similarity_calc=SimilarityCalculator(),
        similarity_threshold=0.6
    )
    
    matched, missing = matcher.match_requirements(dissimilar_evidence, [mock_requirement_no_embedding])
    
    assert len(matched) == 0
    assert len(missing) == 1
    assert missing[0].is_covered == False
    assert missing[0].similarity < 0.6


def test_requirement_matcher_threshold(mock_requirement, matcher_config, mock_ai_service):
    """Test similarity threshold is respected.
    
    With a high threshold of 0.8, evidence that matches at ~0.57 should be in missing list.
    """
    # Create evidence that has moderate similarity (~0.57) but below 0.8 threshold
    moderate_similarity_evidence = [
        ResumeEvidenceUnit(
            id="reu_moderate",
            text="Python development",
            source_section="skills",
            tags={"type": "skill"},
            embedding=[0.8, 0.2, 0.1] * 1024  # Similarity ~0.57 with requirement
        )
    ]
    
    config = MatcherConfig(similarity_threshold=0.8)
    matcher = RequirementMatcher(
        ai_service=mock_ai_service,
        similarity_calc=SimilarityCalculator(),
        similarity_threshold=config.similarity_threshold
    )
    
    matched, missing = matcher.match_requirements(moderate_similarity_evidence, [mock_requirement])
    
    # With threshold 0.8, similarity of ~0.57 is below threshold
    assert len(matched) == 0
    assert len(missing) == 1
    assert missing[0].is_covered == False
    assert missing[0].similarity < 0.8


def test_requirement_embedding_exception(mock_requirement_no_embedding):
    """Test that requirement embedding failure creates missing requirement with similarity=0.0."""
    mock_ai_service = Mock()
    mock_ai_service.generate_embedding.side_effect = Exception("API error")
    
    evidence_units = [
        ResumeEvidenceUnit(
            id="reu_001",
            text="Python development",
            source_section="skills",
            tags={"type": "skill"},
            embedding=[0.8, 0.2, 0.1] * 1024
        )
    ]
    
    matcher = RequirementMatcher(
        ai_service=mock_ai_service,
        similarity_calc=SimilarityCalculator(),
        similarity_threshold=0.5
    )
    
    matched, missing = matcher.match_requirements(evidence_units, [mock_requirement_no_embedding])
    
    # Requirement should be in missing list with similarity=0.0
    assert len(matched) == 0
    assert len(missing) == 1
    assert missing[0].similarity == 0.0
    assert missing[0].evidence is None
    assert missing[0].is_covered == False


def test_requirement_embedding_returns_none(mock_requirement_no_embedding):
    """Test that requirement embedding returning None creates missing requirement with similarity=0.0."""
    mock_ai_service = Mock()
    mock_ai_service.generate_embedding.return_value = None
    
    evidence_units = [
        ResumeEvidenceUnit(
            id="reu_001",
            text="Python development",
            source_section="skills",
            tags={"type": "skill"},
            embedding=[0.8, 0.2, 0.1] * 1024
        )
    ]
    
    matcher = RequirementMatcher(
        ai_service=mock_ai_service,
        similarity_calc=SimilarityCalculator(),
        similarity_threshold=0.5
    )
    
    matched, missing = matcher.match_requirements(evidence_units, [mock_requirement_no_embedding])
    
    # Requirement should be in missing list with similarity=0.0
    assert len(matched) == 0
    assert len(missing) == 1
    assert missing[0].similarity == 0.0
    assert missing[0].evidence is None
    assert missing[0].is_covered == False


def test_embedding_hydration_called_once_per_evidence():
    """Test that evidence embeddings are generated only once per match operation."""
    from core.matcher.requirement_matcher import hydrate_embeddings
    
    mock_ai = Mock()
    mock_ai.generate_embedding.return_value = [0.5, 0.5, 0.5] * 341
    
    evidence_units = [
        ResumeEvidenceUnit(
            id="reu_001",
            text="Python development",
            source_section="skills",
            tags={"type": "skill"},
            embedding=None  # Will need hydration
        ),
        ResumeEvidenceUnit(
            id="reu_002",
            text="AWS cloud",
            source_section="experience",
            tags={"type": "description"},
            embedding=None  # Will need hydration
        )
    ]
    
    from database.models import JobRequirementUnit
    mock_req = Mock(spec=JobRequirementUnit)
    mock_req.embedding_row = Mock()
    mock_req.embedding_row.embedding = [0.6, 0.3, 0.1] * 341
    
    # Call hydrate_embeddings
    hydrate_embeddings(evidence_units, [mock_req], mock_ai)
    
    # Each evidence unit should have been embedded exactly once
    assert mock_ai.generate_embedding.call_count == 2
    
    # Verify both evidence units are hydrated
    assert evidence_units[0].embedding is not None
    assert evidence_units[1].embedding is not None


def test_hydrate_embeddings_returns_requirement_embeddings():
    """Test that hydrate_embeddings returns requirement embeddings dict."""
    from core.matcher.requirement_matcher import hydrate_embeddings
    
    mock_ai = Mock()
    mock_ai.generate_embedding.return_value = [0.5, 0.5, 0.5] * 341
    
    evidence_units = [
        ResumeEvidenceUnit(
            id="reu_001",
            text="Python development",
            source_section="skills",
            tags={"type": "skill"},
            embedding=[0.8, 0.2, 0.1] * 341
        )
    ]
    
    from database.models import JobRequirementUnit
    mock_req = Mock(spec=JobRequirementUnit)
    mock_req.embedding_row = Mock()
    mock_req.embedding_row.embedding = None  # Will need hydration
    
    # Call hydrate_embeddings
    hydrated_evidence, req_embeddings = hydrate_embeddings(evidence_units, [mock_req], mock_ai)
    
    # Should return requirement embeddings dict
    assert mock_req in req_embeddings
    assert req_embeddings[mock_req] is not None


def test_pure_matching_no_ai_calls():
    """Test that _match_with_embeddings does not call AI service."""
    from core.matcher.requirement_matcher import RequirementMatcher
    
    mock_ai = Mock()
    mock_ai.generate_embedding.return_value = [0.1] * 1024
    
    evidence_units = [
        ResumeEvidenceUnit(
            id="reu_001",
            text="Python development",
            source_section="skills",
            tags={"type": "skill"},
            embedding=[0.8, 0.2, 0.1] * 341
        )
    ]
    
    from database.models import JobRequirementUnit
    mock_req = Mock(spec=JobRequirementUnit)
    mock_req.embedding_row = Mock()
    mock_req.embedding_row.embedding = [0.8, 0.2, 0.1] * 341
    
    matcher = RequirementMatcher(
        ai_service=mock_ai,
        similarity_calc=SimilarityCalculator(),
        similarity_threshold=0.5
    )
    
    # Pre-hydrate embeddings
    from core.matcher.requirement_matcher import hydrate_embeddings
    evidence_units, req_embeddings = hydrate_embeddings(evidence_units, [mock_req], mock_ai)
    
    # Clear mock to track AI calls in pure matching
    mock_ai.generate_embedding.reset_mock()
    
    # Call pure matching directly
    matched, missing = matcher._match_with_embeddings(
        evidence_units, [mock_req], req_embeddings
    )
    
    # AI service should not be called during matching
    mock_ai.generate_embedding.assert_not_called()
